package me.twintailedfoxxx.bedwarsevents.objects.enums;

public enum EventType
{
    MODIFY_INVENTORY, ADD_POTION_EFFECT, PARAM_CHANGE, CHANGE_PLACED_BLOCKS, CHANGE_DEFENCE_OBJECT,
    SPAWN_ENTITY, RAIN, TELEPORT, SET_BED_STATUS, CHANGE_SHOP_MULTIPLIERS, CHANGE_PLAYER_ATTRIBUTES,
    VELOCITY_MANIPULATION, EXECUTE_COMMANDS, CHANGE_EMERALD_GENERATOR_MULTIPLIER, TOGGLE_ALLOW_USE_SHOP,
    SCAFFOLD, INVISIBILITY, TOGGLE_GENERATOR
}